stanford_ssp.settings:
  type: mapping
  mapping:
    langcode:
      type: string
      label: 'Language code'
    _core:
      type: _core_config_info
    saml_attribute:
      type: string
      label: 'Attribute in SAML that contains the role mapping values'
    hide_local_login:
      type: boolean
      label: 'Hide core local login form on user page'
    restriction:
      type: string
      label: 'Login restrictions'
    allowed:
      type: mapping
      label: 'Allowed Authorizations'
      mapping:
        affiliations:
          type: sequence
          label: 'Allowed Affiliations'
          sequence:
            type: string
            label: 'Allowed Affiliation'
        groups:
          type: sequence
          label: 'Allowed Groups'
          sequence:
            type: string
            label: 'Allowed Group'
        users:
          type: sequence
          label: 'Allowed Users'
          sequence:
            type: string
            label: 'Allowed User'
